openapi: '3.0.2'
info:
  title: 'SWAGGER - POC'
  description: 'Proof of concept. Learning about api documentation'
  version: '1.0'

servers:
  - url: 'http://localhost:3000'

tags:
  - name: customers
  - name: teste

paths:
  /customers:
    servers:
      - url: 'http://localhost:3000'
    get:
      tags:
      - customers
      summary: 'Get customers array'
      responses:
        '200':
          description: 'Success'
          content:
            application/json:
              schema:
                type: array
                items:
                  type: string
    
    post:
      tags:
      - customers
      summary: 'Create a new customer'
      requestBody:
        description: '<h2>A String name</h2>'
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/reqCreateCustomer'

      responses:
        '200':
          description: 'Success'
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/resCreateCustomer'

components:
  schemas:
    reqCreateCustomer:
      type: object
      properties:
        nome:
         type: string
         example: 'Bruce Wayne'
      
      required:
        - nome
    
    resCreateCustomer:
      type: array
      items:
        type: string
        example: 'Bruce Wayne'