openapi: '3.0.2'
info:
  title: 'SWAGGER - POC'
  description: 'Proof of concept. Learning about api documentation'
  version: '1.0'

servers:
  - url: 'http://localhost:3000'

tags:
  - name: customers

paths:
  /customers:
    servers:
      - url: 'http://localhost:3000'
    get:
      tags:
      - customers
      summary: 'Get customers list'
      responses:
        '200':
          description: 'Success'
          content:
            application/json:
              schema:
                type: array
                items:
                  type: string